### ISSUE TITLE
Migrate to iovalkey

### ISSUE THREAD

**Issue by MonsignorEduardo** [yxx4c/prisma-extension-redis#12]
See
- https://github.com/taskforcesh/bullmq/issues/2490
- https://github.com/redis/node-redis/issues/2658#issuecomment-1968104973

https://github.com/valkey-io/iovalkey

**Comment by yxx4c** [comment]
@MonsignorEduardo ,

Thank you for bringing `iovalkey` to my attention. I will look into this library and may consider migrating to it once I can rewrite the section that handles `auto-caching` to avoid the use of `async-cache-dedupe`. At that point, users won't need to pass a Redis client to the extension, as everything will be managed internally. The choice of any external client won't be a concern unless you're particularly worried about project dependencies.

**Comment by yxx4c** [comment]
Hi @MonsignorEduardo,

I have pushed an updated version of the extension with `iovalkey` to the dev branch, feel free to check it out and share your feedback.

**Comment by yxx4c** [comment]
Hii @li2109,

Thank you for sharing your thoughts! I understand the desire for an interface that allows users to provide their own Redis client. However, I have some concerns about this approach.

Introducing an abstraction for the caching operations could lead to potential issues with implementation stability. Any changes to the abstract operations or future modifications might break existing implementations, and I'm not fully aware of the various libraries that support features like `pipeline`, `unlink`, and how they handle these functionalities.

Regarding the extension, the primary goal is to provide a caching solution for Prisma query results. Users need a Redis cache that supports auto-caching, custom key caching, and cache invalidation. Initially, the extension required users to pass an `ioredis` client, but with the switch to `iovalkey`, I believe this change simplifies the process, as users are no longer required to pass a client just for the extension to use. Although the switch to `iovalkey` did not change how the internal operations were performed, it does mean that the client is now initialized and used directly within the extension. This gives me the ability to enhance the code as long as the core logic is maintained. If users want to utilize the client inside the extension, they can do so by calling `extendedPrisma.redis`, which maintains flexibility.

I appreciate your feedback and will keep it in mind for future enhancements. If you have any further suggestions or specific use cases in mind, I’d be happy to discuss them!

**Comment by yxx4c** [comment]
Migrated to `iovalkey` in this commit [97b97c6](https://github.com/yxx4c/prisma-extension-redis/commit/97b97c63804516f14b0ece49afe17159aca028d1)

**Comment by yxx4c** [comment]
Follow-up for @li2109 and anyone deploying at the edge: the abstraction suggested in this thread ended up shipping — v5 is client-agnostic behind a small `RedisApi` interface, has **zero runtime dependencies**, and the published build imports nothing but the Prisma peer, so it runs in edge runtimes (Cloudflare Workers, Vercel Edge) paired with `@upstash/redis`. Details: [edge runtimes](https://yxx4c.github.io/prisma-extension-redis/ADAPTERS#edge-runtimes-cloudflare-workers-vercel-edge-deno-deploy).
