### ISSUE TITLE
Bug: Missing return statement in getCache function for missed cache | Duplicate: Redis JSON not enabled

### ISSUE THREAD

**Issue by moshOntong-IT** [yxx4c/prisma-extension-redis#20]
```
error: EXECABORT Transaction discarded because of previous errors. {"command":{"args":[],"name":"exec"},"previousErrors":[{"command":{"args":["emerald_api*user*op*find_unique*key*66947619"],"name":"JSON.GET"}}]}
```

Code:
```
 .$extends(
    PrismaExtensionRedis({
      config: {
        type: "JSON",
        ttl: 60,
        stale: 30,
        logger,
        cacheKey: {
          case: CacheCase.SNAKE_CASE,
          delimiter: "*",
          prefix: "emerald_api",
        },
        auto: {},
      },
      client: {
        host: "redis",
        port: parseInt(Bun.env.APP_REDIS_PORT!),
        password: Bun.env.REDIS_PASSWORD!,
      },
    })
  );
  ```

**Comment by yxx4c** [comment]
Hii @moshOntong-IT,

Could you please share the query that triggered this error? Thank you!

**Comment by kalebheitzman** [comment]
I'm getting the same error when I use autocaching on the findMany method. I've noticed my model returns undefined instead of null on a cache miss and have had to implement a retry method into my model to get around this at the moment:

```js
export async function getAssessmentsForUser(
  userId: number,
  maxRetries = 3
): Promise<AssessmentWithScenario[]> {
  const customKey = prisma.getAutoKey({
    args: { where: { userId: userId } },
    model: "Assessment",
    operation: "findMany",
  });

  let retries = 0;
  while (retries < maxRetries) {
    try {
      let assessments: AssessmentWithScenario[] =
        await prisma.assessment.findMany({
          where: { userId: userId },
          orderBy: { id: "asc" },
          cache: { ttl: 5, key: customKey },
        });

      assessments = await Promise.all(
        assessments.map(async (assessment) => {
          assessment.scenario = await getScenarioByKey(
            assessment.scenarioKey || ""
          );
          return assessment;
        })
      );

      return assessments;
    } catch (error) {
      retries++;
    }
  }

  throw new Error("Failed to fetch assessments after multiple retries");
}
```

**Comment by kalebheitzman** [comment]
Does this solve the problem? I don't know how this plugin works well enough to debug it but I think there's a missing return statement at the end of getCache

```js

    const cacheContext = {
      result,
      ttl: ttl * 1000 + timestamp,
      stale: (ttl + stale) * 1000 + timestamp,
    };

    const value = (transformer?.serialize || JSON.stringify)(cacheContext);

    setCache(type, key, value, ttl + stale, redis);

    // return the result
    return result;
  } catch (error) {
```

**Comment by yxx4c** [comment]
Hii @kalebheitzman,

It seems I overlooked that, and you’re absolutely right about the missing return statement. I’ll update the extension and push it shortly. While this should address the issue of needing to retry to get the cache during the initial attempt, I’m not certain if it will resolve the issue the OP mentioned, unless it’s the same scenario.

**Comment by yxx4c** [comment]
Hii @moshOntong-IT @kalebheitzman,

Please take a look at version 2.1.0 of the extension and let me know if it resolves the issue. Thank you for your support!

**Comment by moshOntong-IT** [comment]
> Hii @moshOntong-IT,
> 
> Could you please share the query that triggered this error? Thank you!


```

    logger.info("Checking phone number....");

    const user = await prismaClient.user.findUnique({
      where: {
        phoneNumber,
      },
    });

```

![image](https://github.com/user-attachments/assets/bd8068c9-4c1f-46b9-8474-00c40e555606)

**Comment by moshOntong-IT** [comment]
> > Hii @moshOntong-IT,
> > Could you please share the query that triggered this error? Thank you!
> 
> ```
> 
>     logger.info("Checking phone number....");
> 
>     const user = await prismaClient.user.findUnique({
>       where: {
>         phoneNumber,
>       },
>     });
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/57244338/387544791-bd8068c9-4c1f-46b9-8474-00c40e555606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDIwNTksIm5iZiI6MTczMjAwMTc1OSwicGF0aCI6Ii81NzI0NDMzOC8zODc1NDQ3OTEtYmQ4MDY4YzktNGMxZi00NmI5LTg0NzQtMDBjNDBlNTU1NjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA3MzU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYzE0YTA3MDU3ZGQ3OWFkZjdjNmE1ODZlZTk4OWYyZjE3NTFmODRmMTI3ZWY2NDI4OTAwOTVjNjIzZDE3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VO4IcfUydyJM67-nHEmaMehnHFzUDyK0ejqdh0OdxeY)

Here is the code. I am using here  `findUnique`

**Comment by moshOntong-IT** [comment]
@yxx4c I tried to turn off the auto.

but there is query that `cache` is true

```

    const threads = await prismaConfig.thread.findMany({
      where: queries,
      include: {
        author: true,
      },
      cache: true,
    });
```



Then the error occured here

**Comment by yxx4c** [comment]
Hi @moshOntong-IT 

Were you able to check the latest version v2.1.0?

**Comment by moshOntong-IT** [comment]
@yxx4c 
![image](https://github.com/user-attachments/assets/694b7841-2d27-4ea3-a45d-9b8134935572)

**Comment by moshOntong-IT** [comment]
weird whe nI turned the type from JSON into string it is now working

**Comment by kalebheitzman** [comment]
> I’m not certain if it will resolve the issue the OP mentioned, unless it’s the same scenario.

In my case, I had a query that was dependent upon another query in my loader. I was loading a user but the user was being returned undefined. When I tried to query on the user id in the next query down the line I was getting the same exact error as the OP. Essentially bad code on my part because I was relying on a null check and not both a null/undefined check.

**Comment by moshOntong-IT** [comment]
> > I’m not certain if it will resolve the issue the OP mentioned, unless it’s the same scenario.
> 
> In my case, I had a query that was dependent upon another query in my loader. I was loading a user but the user was being returned undefined. When I tried to query on the user id in the next query down the line I was getting the same exact error as the OP. Essentially bad code on my part because I was relying on a null check and not both a null/undefined check.

did you use "JSON" instead of "STRING"?

**Comment by kalebheitzman** [comment]
I was using JSON

**Comment by yxx4c** [comment]
@moshOntong-IT 

This issue appears to be another case of https://github.com/yxx4c/prisma-extension-redis/issues/7, likely due to the Redis instance missing the JSON module.

The functionality for utilizing the string type was reintroduced in https://github.com/yxx4c/prisma-extension-redis/commit/f9641c8004a7a0ea81864bb13ee82b5e2c8aac95.




@kalebheitzman 

The problem you encountered was a legitimate bug in the code.

**Comment by kalebheitzman** [comment]
@yxx4c thanks and you're right. I forgot that I had to install the JSON module in Redis. I hadn't made the connection that I was actually experiencing two different problems.

**Comment by moshOntong-IT** [comment]
> @moshOntong-IT
> 
> This issue appears to be another case of #7, likely due to the Redis instance missing the JSON module.
> 
> The functionality for utilizing the string type was reintroduced in [f9641c8](https://github.com/yxx4c/prisma-extension-redis/commit/f9641c8004a7a0ea81864bb13ee82b5e2c8aac95).
> 
> @kalebheitzman
> 
> The problem you encountered was a legitimate bug in the code.

I am using docker how can maybe install JSON module?

**Comment by kalebheitzman** [comment]
@yxx4c a couple of questions I can't figure out from the documentation (likely I may not be reading it correctly...).

- Do you have to use JSON instead of STRING in order to use uncaching? Or will uncaching work with both?
- Does the autocache automatically provide uncaching on updates/upserts etc, or do I need to implement uncache myself for the relevant methods in my models?

**Comment by yxx4c** [comment]
@kalebheitzman 

- Uncache is compatible with both JSON and STRING type caches. The JSON type was added later in the extension's development, as its predictable keys allow for direct utilization from Redis.

- Auto-Cache currently does not support Auto-Uncache functionality; this feature is not available at this time. However, version 2.0.0 represents progress toward making this possible in the future. In the meantime, I have implemented a workaround to Uncache Auto-Cached entries by using `extendedPrisma.getAutoKey()` with the same arguments that were used in the Auto-Cached queries (see example code for reference).

**Comment by yxx4c** [comment]
@moshOntong-IT @kalebheitzman,

Thank you both for your support and interest in the library! I hope the previous comments were helpful and that the fixes I pushed resolved your issues. I’ll go ahead and close this issue as completed.

**Comment by kalebheitzman** [comment]
Thanks @yxx4c!

**Comment by yxx4c** [comment]
A quality-of-life follow-up for everyone who hit the cryptic `EXECABORT`/`JSON.GET` errors in this thread: since v5, a `type: 'JSON'` config **probes the server for RedisJSON at startup** and announces the exact remedy if it's missing (switch to `type: 'STRING'`, or use a JSON-capable server — note that Redis 8 now ships JSON natively, and Dragonfly/Redis Stack always had it). `healthCheck()` also reports `jsonSupport`. The silent no-cache failure mode is gone. Thanks @kalebheitzman and @moshOntong-IT for surfacing how confusing this was.
