### ISSUE TITLE
Error when query has cache: false 

### ISSUE THREAD

**Issue by mfchiz** [yxx4c/prisma-extension-redis#22]
Nice work on this library!

This query fails and throws an error.

  const caseFile = await db.caseFile.findUnique({
    cache: false,
    where: {
    id: case.id
    },
  })

This is because when the extension checks isAutoCacheEnabled and it is false and isCustomCacheEnabled and isCustomUncacheEnabled are also false. The cache field needs to be removed from args by setting it to undefined before "return query(args);" on line 72. Otherwise prisma throws an error.

**Comment by yxx4c** [comment]
Hi @mfchiz,

Happy to hear that you like the library! You are right about the bug. I’ve just fixed it and released v2.1.1. Thanks for pointing it out! I’d love for you to check it out and let me know if you have any feedback.
