### ISSUE TITLE
Use lodash-es instead of lodash

### ISSUE THREAD

**Issue by jeky1950** [yxx4c/prisma-extension-redis#4]
This is just a request. Its ok if this is not possible. I want to be able to import @yxx4c/prisma-redis-extension as an ES module. Right now if I try to do that I get this error:

```
ERROR  [worker reload] [worker init] The requested module 'lodash' does not provide an export named 'camelCase'

 import { camelCase, kebabCase, snakeCase, startCase } from "lodash";     
 ^^^^^^^^^
 SyntaxError: The requested module 'lodash' does not provide an export named 'camelCase'
 at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)  
 at async ModuleJob.run (node:internal/modules/esm/module_job:190:5) 
```

Because of that I now have to instantiate my prisma client inside a .cjs file which mean I dont have TS support in that file. I would really like to be able to have this functionality.

**Comment by yxx4c** [comment]
Hi there,

It should work fine as an ES module, but I’d like to check further. Could you please provide some details about your environment? Specifically, it would be helpful to know:

1. Which JavaScript runtime you are using (Node, Deno, Bun)?
2. Are you using `lodash` in your project?.
3. Any relevant configurations in your `package.json` and `tsconfig.json`.

Thank you!

**Comment by jeky1950** [comment]
Node Version: v18.17.1
NPM Version: 10.2.0

**Comment by yxx4c** [comment]
Hi @jeky1950,

Would it be possible for you to share your `tsconfig.json` and your `run command`?

**Comment by yxx4c** [comment]
Hi @jeky1950 ,

I wanted to give you a quick update: I've removed `lodash` from the package since it wasn't being used directly. And switched to `lodash-es` in the `cache-utils` dependency that this package relies on. I'm not sure if this would help you, but please check and let me know.

**Comment by jeky1950** [comment]
> Hi @jeky1950,
> 
> Would it be possible for you to share your `tsconfig.json` and your `run command`?

Hi, my tsconfig.json looks like this:

```
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}
```

**Comment by jeky1950** [comment]
@yxx4c I have now upgraded my @yxx4c/prisma-redis-extension to v0.1.0 and can now import it has a ES module. However when I try to cache using this code:

```
const product = await prisma.product.findMany({
            where: {
                  name: {
                       contains: search
                  },
            },
            take: 5,
            cache: { ttl: 60, key: getCacheKey([ { prisma: 'Product' }, { search } ]) }
        });
```
I now get this error

```
 ERROR  EXECABORT Transaction discarded because of previous errors.        

  at parseError (node_modules\redis-parser\lib\parser.js:179:12)
  at parseType (node_modules\redis-parser\lib\parser.js:302:14)
```

My prisma client file (dt.ts) looks like this:

```
import { PrismaClient } from '@prisma/client'
import { Redis } from 'ioredis'
import { getCacheKey, getCacheKeyPattern, PrismaRedisExtension, type CacheConfig } from '@yxx4c/prisma-redis-extension'

const redis = new Redis()

const cache: CacheConfig = {
  ttl: 60,
  storage: {
    type: 'redis',
    options: {
      client: redis,
      invalidation: { referencesTTL: 60 }, 
      log: console
    }
  }
}

const prismaClientSingleton = () => {
  const client = new PrismaClient()
  return client.$extends(
    PrismaRedisExtension({ cache, redis })
  )
}

declare const globalThis: {
  prismaGlobal: ReturnType<typeof prismaClientSingleton>;
} & typeof global;

const prisma = globalThis.prismaGlobal ?? prismaClientSingleton()

export { prisma, getCacheKey, getCacheKeyPattern }

if (process.env.NODE_ENV !== 'production') globalThis.prismaGlobal = prisma
```

**Comment by yxx4c** [comment]
Hi @jeky1950,

Could you please verify the version of `ioredis` and its dependencies that you are currently using? I recently updated to the latest version, and I suspect there may be a type mismatch related to this.

**Comment by jeky1950** [comment]
I am on ioredis version 5.4.1

**Comment by yxx4c** [comment]
Will continue the discussion in [issue 5](https://github.com/yxx4c/prisma-extension-redis/issues/5)
