### ISSUE TITLE
Custom cache configurations not working

### ISSUE THREAD

**Issue by jeky1950** [yxx4c/prisma-extension-redis#5]
Node Version: v18.17.1
NPM Version: 10.2.0
Prisma Client: 5.17.0
prisma-extension-redis: 1.0.0
ioredis: 5.4.1
Redis Server: 7.4.0

Hi, when I try to cache using `cache: true` it works but when I try to cache using a custom cache configurations I get an error. Here is the code I used:

```
try {
      const product = await prisma.product.findMany({
            where: {
                name: {
                      contains: search
                }
            },
            take: 5,
            cache: { ttl: 60 * 5, key: getCacheKey([ { prisma: 'Product' }, { search } ]) }
        });
} catch (error) {
    console.error(error)
}
```

I get this error:

 ```
ERROR  EXECABORT Transaction discarded because of previous errors.        

  at parseError (node_modules\redis-parser\lib\parser.js:179:12)
  at parseType (node_modules\redis-parser\lib\parser.js:302:14)
```

My prisma client looks like this:

```
import { PrismaClient } from '@prisma/client'
import { Redis } from 'ioredis'
import { getCacheKey, getCacheKeyPattern, PrismaExtensionRedis, type CacheConfig } from 'prisma-extension-redis'

const redis = new Redis()

const cache: CacheConfig = {
  ttl: 60,
  storage: {
    type: 'redis',
    options: {
      client: redis,
      invalidation: { referencesTTL: 60 }, 
      log: console
    }
  }
}

const prismaClientSingleton = () => {
  const client = new PrismaClient()
  return client.$extends(
    PrismaExtensionRedis({ cache, redis })
  )
}

declare const globalThis: {
  prismaGlobal: ReturnType<typeof prismaClientSingleton>;
} & typeof global;

const prisma = globalThis.prismaGlobal ?? prismaClientSingleton()

export { prisma, getCacheKey, getCacheKeyPattern }

if (process.env.NODE_ENV !== 'production') globalThis.prismaGlobal = prisma
```

**Comment by jeky1950** [comment]
So I have been doing more tests and if I say **cache: true**, it works however its when I try to do a custom cache configuration I get the error I spoke of above. Here is the custom configuration that I am using:

`cache: { ttl: 60, key: getCacheKey([ { prisma: 'Product' }, { search } ]) }`

**Comment by yxx4c** [comment]
Hi @jeky1950 ,

Could you provide an example project that I can use to replicate this bug?

**Comment by jeky1950** [comment]
Hi @yxx4c 

[Here](https://github.com/jeky1950/customized-cache-error) is a repo with the bug reproduced

**Comment by yxx4c** [comment]
Hi @jeky1950,

Thanks for sharing the repo. I ran some tests and didn't encounter the error you mentioned. Could you please try deleting the `node_modules` folder and any other relevant cache? If you haven't done this already, it could help resolve the issue.

The only difference in our environments is that I'm using DragonflyDB instead of Redis, but I don't think that should lead to the error you're experiencing. I suspect it might be related to the cached files, but please keep me updated if that's not the case. Additionally, if you're on Discord, feel free to reach out to me there (same ID).

**Comment by jeky1950** [comment]
Hi @yxx4c 

Thank you for your suggestion. Unfortunately it wasn't the problem. You see I am still new to Redis and after some time trying to find a solution to this error message that I was getting on the repo I had sent you:

```
ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (C:\Users\Antony\Documents\customized-cache-error\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\Users\Antony\Documents\customized-cache-error\node_modules\redis-parser\lib\parser.js:302:14) {
  command: { name: 'exec', args: [] },
  previousErrors: [
    ReplyError: ERR unknown command 'JSON.GET', with args beginning with: 'prisma:user'
        at parseError (C:\Users\Antony\Documents\customized-cache-error\node_modules\redis-parser\lib\parser.js:179:12)
        at parseType (C:\Users\Antony\Documents\customized-cache-error\node_modules\redis-parser\lib\parser.js:302:14) {
      command: [Object]
    }
  ]
}
```

I was able to determine that the error was because I did have the [RedisJSON](https://github.com/RedisJSON/RedisJSON) module installed on my redis server. And this ultimately fixed my problem. Thanks again for all your help. You have create an amazing tool and I appreciate all the work that you have put into it. I hope more people get to use it. 

Sincerely from Zimbabwe
