### ISSUE TITLE
Custom cache configuration using JSON Type of Redis

### ISSUE THREAD

**Issue by sid-js** [yxx4c/prisma-extension-redis#7]
Hey, I have Redis hosted on a cloud provider called aiven, which does not support RedisJSON. 

While using your library, autocaching works well because it stores it as Strings in the Redis DB. But I am unable to use custom cache configuration and invalidation since it's using RedisJSON. Is there any workaround for this ?

**Comment by yxx4c** [comment]
Hi @sid-js,

I have added the option to use STRING in the latest version v1.2.0. Please don't hesitate to let me know if anything.
